-- MySQL Script generated by MySQL Workbench
-- Thu Apr 28 03:04:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Triplona
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Triplona
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Triplona` ;
USE `Triplona` ;

-- -----------------------------------------------------
-- Table `Triplona`.`user_accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Triplona`.`user_accounts` (
  `user_name` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `email_id` VARCHAR(45) NULL,
  `password` CHAR(50) NULL,
  `date_of_birth` DATE NULL,
  `nic_passport_no` VARCHAR(45) NULL,
  `mobile_no` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `province_state` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `zip_code` VARCHAR(45) NULL,
  `payment_method` VARCHAR(45) NULL,
  `credit_card_type` VARCHAR(45) NULL,
  `cardholder_name` VARCHAR(45) NULL,
  `credit_card_no` VARCHAR(45) NULL,
  `expiration_date` DATE NULL,
  `user_id` INT(10) NOT NULL AUTO_INCREMENT,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Triplona`.`corporate_accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Triplona`.`corporate_accounts` (
  `corp_id` INT(10) NOT NULL AUTO_INCREMENT,
  `corp_name` VARCHAR(45) NULL,
  `email_id` VARCHAR(45) NULL,
  `password` CHAR(50) NULL,
  `registraction_no` VARCHAR(45) NULL,
  `company_type` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `province_state` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `zip_code` VARCHAR(45) NULL,
  `payment_method` VARCHAR(45) NULL,
  `credit_card_type` VARCHAR(45) NULL,
  `cardholder_name` VARCHAR(45) NULL,
  `credit_card_no` VARCHAR(45) NULL,
  `expiration_date` DATE NULL,
  PRIMARY KEY (`corp_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`corp_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Triplona`.`hotel_accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Triplona`.`hotel_accounts` (
  `hotel_id` INT(10) NOT NULL AUTO_INCREMENT,
  `hotel_username` VARCHAR(45) NULL,
  `hotel_name` VARCHAR(45) NULL,
  `email_id` VARCHAR(45) NULL,
  `password` CHAR(50) NULL,
  `registration_no` VARCHAR(45) NULL,
  `hotel_type` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `province_state` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `zip_code` VARCHAR(45) NULL,
  `rating` INT(10) NULL,
  PRIMARY KEY (`hotel_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`hotel_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Triplona`.`food_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Triplona`.`food_services` (
  `food_service_id` INT(10) NOT NULL AUTO_INCREMENT,
  `hotel_id` INT(10) NULL,
  `food_type` VARCHAR(45) NULL,
  `qty` INT(10) NULL,
  `user_type` VARCHAR(45) NULL,
  `servings` VARCHAR(45) NULL,
  `price` FLOAT(20) NULL,
  `no_of_people` INT(10) NULL,
  `no_of_childern` INT(10) NULL,
  `food_service_avail_id` INT(10) NULL,
  PRIMARY KEY (`food_service_id`),
  INDEX `fk_food_services_hotel_accounts1_idx` (`hotel_id` ASC) VISIBLE,
  CONSTRAINT `fk_food_services_hotel_accounts1`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `Triplona`.`hotel_accounts` (`hotel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Triplona`.`room_services_availablity_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Triplona`.`room_services_availablity_record` (
  `room_service_avail_update_id` INT(10) NOT NULL AUTO_INCREMENT,
  `datetime` DATETIME(6) NULL,
  `availbility` INT(10) NULL,
  `room_service_id` INT(10) NULL,
  PRIMARY KEY (`room_service_avail_update_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Triplona`.`room_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Triplona`.`room_services` (
  `room_service_id` INT(10) NOT NULL AUTO_INCREMENT,
  `hotel_id` INT(10) NULL,
  `service_type` VARCHAR(45) NULL,
  `qty` INT(10) NULL,
  `services` VARCHAR(45) NULL,
  `price` FLOAT(20) NULL,
  `no_of_people` INT(10) NULL,
  `no_of_childern` INT(10) NULL,
  `room_service_avail_id` INT(10) NULL,
  PRIMARY KEY (`room_service_id`),
  INDEX `fk_room_services_hotel_accounts1_idx` (`hotel_id` ASC) VISIBLE,
  INDEX `fk_room_services_room_services_availablity_record1_idx` (`room_service_avail_id` ASC) VISIBLE,
  CONSTRAINT `fk_room_services_hotel_accounts1`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `Triplona`.`hotel_accounts` (`hotel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_services_room_services_availablity_record1`
    FOREIGN KEY (`room_service_avail_id`)
    REFERENCES `Triplona`.`room_services_availablity_record` (`room_service_avail_update_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Triplona`.`package_availablity_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Triplona`.`package_availablity_record` (
  `package_avail_update_id` INT(10) NOT NULL AUTO_INCREMENT,
  `datetime` DATETIME(6) NULL,
  `availbility` INT(10) NULL,
  `package_service_id` INT(10) NULL,
  PRIMARY KEY (`package_avail_update_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Triplona`.`room_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Triplona`.`room_type` (
  `room_type_id` INT(10) NOT NULL AUTO_INCREMENT,
  `room_type` VARCHAR(45) NULL,
  `total_qty` INT(10) NULL,
  `qty` INT(10) NULL,
  `user_type` VARCHAR(45) NULL,
  `no_of_beds` VARCHAR(45) NULL,
  `price` FLOAT(20) NULL,
  `no_of_adult` INT(10) NULL,
  `no_of_childern` INT(10) NULL,
  `hotel_id` INT(10) NULL,
  PRIMARY KEY (`room_type_id`),
  INDEX `fk_room_type_hotel_accounts1_idx` (`hotel_id` ASC) VISIBLE,
  CONSTRAINT `fk_room_type_hotel_accounts1`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `Triplona`.`hotel_accounts` (`hotel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Triplona`.`packages_deals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Triplona`.`packages_deals` (
  `package_deal_id` INT(10) NOT NULL AUTO_INCREMENT,
  `hotel_id` INT(10) NULL,
  `package_type` VARCHAR(45) NULL,
  `qty` INT(10) NULL,
  `services` VARCHAR(45) NULL,
  `servings` VARCHAR(45) NULL,
  `price` FLOAT(20) NULL,
  `no_of_people` INT(10) NULL,
  `no_of_childern` INT(10) NULL,
  `package_avail_id` INT(10) NULL,
  `food_service_id` INT(10) NULL,
  `room_service_id` INT(10) NULL,
  `room_type_id` INT(10) NULL,
  PRIMARY KEY (`package_deal_id`),
  INDEX `fk_packages_deals_hotel_accounts1_idx` (`hotel_id` ASC) VISIBLE,
  INDEX `fk_packages_deals_room_services1_idx` (`room_service_id` ASC) VISIBLE,
  INDEX `fk_packages_deals_food_services1_idx` (`food_service_id` ASC) VISIBLE,
  INDEX `fk_packages_deals_room_type1_idx` (`room_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_packages_deals_hotel_accounts1`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `Triplona`.`hotel_accounts` (`hotel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_packages_deals_room_services1`
    FOREIGN KEY (`room_service_id`)
    REFERENCES `Triplona`.`room_services` (`room_service_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_packages_deals_food_services1`
    FOREIGN KEY (`food_service_id`)
    REFERENCES `Triplona`.`food_services` (`food_service_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_packages_deals_package_availablity_record1`
    FOREIGN KEY (`room_service_id`)
    REFERENCES `Triplona`.`package_availablity_record` (`package_avail_update_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_packages_deals_room_type1`
    FOREIGN KEY (`room_type_id`)
    REFERENCES `Triplona`.`room_type` (`room_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Triplona`.`promotion_discounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Triplona`.`promotion_discounts` (
  `promo_dis_id` INT(10) NOT NULL AUTO_INCREMENT,
  `promo_dis_title` VARCHAR(45) NULL,
  `details` VARCHAR(45) NULL,
  `discount` FLOAT(20) NULL,
  `promo_availability` VARCHAR(45) NULL,
  `start_date` DATE NULL,
  `expiration_date` DATE NULL,
  `promo_dis_code` VARCHAR(45) NULL,
  PRIMARY KEY (`promo_dis_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Triplona`.`user_booking_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Triplona`.`user_booking_record` (
  `booking_id` INT(10) NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) NULL,
  `hotel_id` INT(10) NULL,
  `package_id` INT(10) NULL,
  `qty` INT(10) NULL,
  `payment_type` VARCHAR(45) NULL,
  `payment_amount` FLOAT(20) NULL,
  `payment_amount_status` INT NULL,
  `no_of_people` INT(10) NULL,
  `no_of_childern` INT(10) NULL,
  `checkin` DATETIME(6) NULL,
  `checkout` DATETIME(6) NULL,
  `promo_dis_id` INT(10) NULL,
  PRIMARY KEY (`booking_id`),
  UNIQUE INDEX `booking_id_UNIQUE` (`booking_id` ASC) VISIBLE,
  INDEX `fk_booking_record_user_accounts1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_booking_record_hotel_accounts1_idx` (`hotel_id` ASC) VISIBLE,
  INDEX `fk_booking_record_packages_deals1_idx` (`package_id` ASC) VISIBLE,
  INDEX `fk_user_booking_record_promotion_discounts1_idx` (`promo_dis_id` ASC) VISIBLE,
  CONSTRAINT `fk_booking_record_user_accounts1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Triplona`.`user_accounts` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_record_hotel_accounts1`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `Triplona`.`hotel_accounts` (`hotel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_record_packages_deals1`
    FOREIGN KEY (`package_id`)
    REFERENCES `Triplona`.`packages_deals` (`package_deal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_booking_record_promotion_discounts1`
    FOREIGN KEY (`promo_dis_id`)
    REFERENCES `Triplona`.`promotion_discounts` (`promo_dis_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Triplona`.`employee_accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Triplona`.`employee_accounts` (
  `employee_id` INT(10) NOT NULL AUTO_INCREMENT,
  `corp_id` INT(10) NULL,
  `employee_corp_id` VARCHAR(45) NULL,
  `employee_name` VARCHAR(45) NULL,
  `employee_type` VARCHAR(45) NULL,
  `email_id` VARCHAR(45) NULL,
  `password` CHAR(50) NULL,
  `nic_passport_no` VARCHAR(45) NULL,
  `mobile_no` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `province_state` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `zip_code` VARCHAR(45) NULL,
  UNIQUE INDEX `user_id_UNIQUE` (`employee_id` ASC) VISIBLE,
  PRIMARY KEY (`employee_id`),
  INDEX `fk_employee_accounts_corporate_accounts1_idx` (`corp_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_accounts_corporate_accounts1`
    FOREIGN KEY (`corp_id`)
    REFERENCES `Triplona`.`corporate_accounts` (`corp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Triplona`.`corporate_booking_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Triplona`.`corporate_booking_record` (
  `booking_id` INT(10) NOT NULL AUTO_INCREMENT,
  `employee_id` INT(10) NULL,
  `corp_id` INT(10) NULL,
  `hotel_id` INT(10) NULL,
  `package_id` INT(10) NULL,
  `qty` INT(10) NULL,
  `payment_type` VARCHAR(45) NULL,
  `payment_amount` FLOAT(20) NULL,
  `payment_amount_status` INT NULL,
  `no_of_people` INT(10) NULL,
  `no_of_childern` INT(10) NULL,
  `checkin` DATETIME(6) NULL,
  `checkout` DATETIME(6) NULL,
  PRIMARY KEY (`booking_id`),
  UNIQUE INDEX `booking_id_UNIQUE` (`booking_id` ASC) VISIBLE,
  INDEX `fk_booking_record_hotel_accounts1_idx` (`hotel_id` ASC) VISIBLE,
  INDEX `fk_booking_record_packages_deals1_idx` (`package_id` ASC) VISIBLE,
  INDEX `fk_corporate_booking_record_employee_accounts1_idx` (`employee_id` ASC) VISIBLE,
  INDEX `fk_corporate_booking_record_corporate_accounts1_idx` (`corp_id` ASC) VISIBLE,
  CONSTRAINT `fk_booking_record_hotel_accounts10`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `Triplona`.`hotel_accounts` (`hotel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_record_packages_deals10`
    FOREIGN KEY (`package_id`)
    REFERENCES `Triplona`.`packages_deals` (`package_deal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_corporate_booking_record_employee_accounts1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `Triplona`.`employee_accounts` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_corporate_booking_record_corporate_accounts1`
    FOREIGN KEY (`corp_id`)
    REFERENCES `Triplona`.`corporate_accounts` (`corp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Triplona`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Triplona`.`rooms` (
  `room_avail_update_id` INT(10) NOT NULL AUTO_INCREMENT,
  `datetime` DATETIME(6) NULL,
  `availbility` INT(10) NULL,
  `room_type_id` INT(10) NULL,
  `qty` INT(10) NULL,
  PRIMARY KEY (`room_avail_update_id`),
  INDEX `fk_room_availablity_record_room_type1_idx` (`room_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_room_availablity_record_room_type1`
    FOREIGN KEY (`room_type_id`)
    REFERENCES `Triplona`.`room_type` (`room_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Triplona`.`food_services_availablity_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Triplona`.`food_services_availablity_record` (
  `food_service_avail_update_id` INT(10) NOT NULL AUTO_INCREMENT,
  `datetime` DATETIME(6) NULL,
  `availbility` INT(10) NULL,
  `food_service_id` INT(10) NULL,
  PRIMARY KEY (`food_service_avail_update_id`),
  INDEX `fk_food_services_availablity_record_food_services1_idx` (`food_service_id` ASC) VISIBLE,
  CONSTRAINT `fk_food_services_availablity_record_food_services1`
    FOREIGN KEY (`food_service_id`)
    REFERENCES `Triplona`.`food_services` (`food_service_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Triplona`.`user_activity_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Triplona`.`user_activity_log` (
  `user_activity_id` INT(10) NOT NULL AUTO_INCREMENT,
  `activtiy` VARCHAR(45) NULL,
  `datetime` DATETIME(6) NULL,
  `user_id` INT(10) NULL,
  PRIMARY KEY (`user_activity_id`),
  INDEX `fk_user_activity_log_user_accounts1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_activity_log_user_accounts1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Triplona`.`user_accounts` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Triplona`.`corporate_activity_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Triplona`.`corporate_activity_log` (
  `corp_activity_id` INT(10) NOT NULL AUTO_INCREMENT,
  `activtiy` VARCHAR(45) NULL,
  `datetime` DATETIME(6) NULL,
  `corp_id` INT(10) NULL,
  PRIMARY KEY (`corp_activity_id`),
  INDEX `fk_corporate_activity_log_corporate_accounts1_idx` (`corp_id` ASC) VISIBLE,
  CONSTRAINT `fk_corporate_activity_log_corporate_accounts1`
    FOREIGN KEY (`corp_id`)
    REFERENCES `Triplona`.`corporate_accounts` (`corp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Triplona`.`hotel_activity_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Triplona`.`hotel_activity_log` (
  `hotel_activity_id` INT(10) NOT NULL AUTO_INCREMENT,
  `activtiy` VARCHAR(45) NULL,
  `datetime` DATETIME(6) NULL,
  `hotel_id` INT(10) NULL,
  PRIMARY KEY (`hotel_activity_id`),
  INDEX `fk_hotel_activity_log_hotel_accounts1_idx` (`hotel_id` ASC) VISIBLE,
  CONSTRAINT `fk_hotel_activity_log_hotel_accounts1`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `Triplona`.`hotel_accounts` (`hotel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Triplona`.`admin_accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Triplona`.`admin_accounts` (
  `admin_id` INT(10) NOT NULL AUTO_INCREMENT,
  `admin_name` VARCHAR(45) NULL,
  `admin_type` VARCHAR(45) NULL,
  `email_id` VARCHAR(45) NULL,
  `password` CHAR(50) NULL,
  `admin_accounts_control` INT(10) NULL,
  `all_accounts_control` INT(10) NULL,
  `cms_control` INT(10) NULL,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Triplona`.`admin_activity_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Triplona`.`admin_activity_log` (
  `admin_activity_id` INT(10) NOT NULL AUTO_INCREMENT,
  `activtiy` VARCHAR(45) NULL,
  `datetime` DATETIME(6) NULL,
  `admin_id` INT(10) NULL,
  PRIMARY KEY (`admin_activity_id`),
  INDEX `fk_admin_activity_log_admin_accounts1_idx` (`admin_id` ASC) VISIBLE,
  CONSTRAINT `fk_admin_activity_log_admin_accounts1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `Triplona`.`admin_accounts` (`admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
